<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer      $this
 * @var \Zend\Db\Metadata\Object\TableObject $table
 * @var \Zend\Db\Adapter\Adapter $adapter
 */

$rowsCount = $this->tableHelper()->getRowsCount($adapter, $table->getName());
$tableSize = $this->tableHelper()->getTableSize($adapter, $table->getName());
?>
<table class="table table-condensed table-hover">
    <caption class="well well-sm">
        <strong>Table info</strong>
    </caption>
    <thead class="thead-dark">
    <th>Rows count</th>
    <th>Disk space usage</th>
    </thead>
    <tbody>
        <tr>
            <td>
                <?= $rowsCount ?>
            </td>
            <td>
                <span class="col-lg-3"><?= $tableSize ?></span>
                <span class="col-lg-3 text-right">KBytes</span>
            </td>
        </tr>
    </tbody>
</table>



